"""
Django settings for oct14_backend project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oi3^hcp@984&v9y0s0uyy3)9kim%wyo)a)8t6x3t19*zaz0$lk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.29.155.121', 'localhost', '127.0.0.1']



PRIVATE_KEY = '''-----BEGIN PRIVATE KEY-----
MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDMkPbacFhD7IjA
8TvCkYAxJkVkeq+Lf8OWXfyQdyTMagII1ibyCu8gY+Kz4T7iehU4g8szTHYfB1wI
eA4DcrP1T5MlCT1S4nFpKRdO/cVXRUHpo5by9g7cjDD9+oAu93oOFc4lpx9D4EMa
NNTEanpFCe2Pb3AnVS6pkMGtXJkJkxMxoH3Xdm0n0o0w2my3dlPpfdweKdte2TzC
dKF5VFeVvuUFfuEr/r8vdV9j15lbzCjfrqLkxhufoW/mifFHSwruP7MFiwbHLZao
HBpAAH11KyNn3c140Gecobx7xzNhAZY1PT72Hntd23Mo/SufMts0kf20Y32WIuWO
1/Qt0wVfLNlZ96yB3lj1y7KCZFQMfQKvOYqpGiqVrft84rMha+xsoM+/uB0Ou6d3
kDpZj6TtqGhKSMsxDq5/5DDdg7Lk6U9LdHM8i6FjkmuTiEB9S/U4qYHMpCIh40Fw
Ab7wDkFKwphoCGf6yirAREm0gOMgsdQkY9YOjaCOVe33dKZTO2+KJLvCjSKRf0cu
a5bRkTyLbFP0yZeK73z5dvHr2xr13QA/OhOk3D5fOkI/CzlCFupVtXlufOhW/pos
S0mXufriz2AoItdMWIEEaXo+7oXFpXdObJ9fDfHsxD8VGu00OKCT7seZ2xE6Yyj2
wwwqGShMXDdKzOV0X3J6i33v5Yf6eQIDAQABAoICAB/JYMpFjbmUPhW5Bl+v6zr3
5u17kN58zmAFn7K1CL9Is6M635dZspmWW8o2tGZNsRF0jTUd6vbcVmUsfoTzpFn4
cPVez6wa6qN8EpagITNz3A+Zb2G2cU287PnyHEvwAYPByKQaKWYLKXIfhnY002X5
6nOQzd0Ww+buSuIM0uzlcSSTeyppSQHYmj7emekSFmzgNT1spJ1C5UmUBOlM/UUU
AhNOCWAkOAIAW3+wpzBX83v6b25cCDvQQoqQobDBzOODe2ZfmYCGqXPa1gte6B+2
Qcyobv6YZ5kzmo2jQO0QaY5BQ5DL4MCPUoAqgsY8iUpMax9GHGQhbQk6rkMWmK1P
oT//zA4Jw+hfORLms8JBkU8X+kNm9rS7CGiUY3UePffDhAelJUqSQOxAMXk/2WiD
dtE10W8zpDxJ5Yw+sKd0cvarASP8i6t/N6OGQJ84qHVCvcCExwaCEYB37kW3HJeN
YM7cf+b0W/ywdfPOVSEOtBHo9r+NZ0E14YBeMvOZiwrWTTYHsKN2eixzivuquVyZ
GqO+0HZDeNUu3+l0ZXNFopEomDRWAtVCP4/ADm8mN6MGCBImsMeMf7ZXX1BraEVp
Aif9E2pvwAOu4ZgyKkx/Hlfu2IlJbRQrZAcEyyjZHdNphNxbRBmv55BpMw9J/Uyr
lk0zKEojpzU94p66T965AoIBAQDvtfxV504iCNoLjn5tN4zl5Zl54BBSlZBHak2u
0vsJvGa8+Z2Tor5PkDA61DMHv+8b98M8tZCbeQp3Q7X64RZYKK/SdrffrjVLoGR2
2PBTM4XYlwAKHBfZ5pD3s7joiYV5a4CRiN53rAYUzPKTxicgL2vZZ8sZNzYkUJLJ
XoVjPzGVHfkOl/O6MOTUpYhAobBXArcaFBr2n9uZUFpBa5IHI5x369Q6GMsmS03Z
2zt98FDvO9yyl8gyx9h9Cm/PBDdW6UHyvpISYRtFTnfuKUufqk/u447hNmOrTPF3
X7v3ULy7vSD5ZnFCdchr1yJpUmgaMOwGib6P+nws4MP19ojFAoIBAQDad5owm2nD
YNWywXTBdhgCt9wi2tDbvZpHVCt/8cJqGqerqBmxBG7tSpydHTZFqaH6gEXFanth
kCLA6AXHnltdxPQlnhKGU2+QiN/b0VKK1UiZnJlHvlYhCQ5woPm/vCc6G7dAzdqk
C+R4WSq/WYyicgnTbfYfz+HmdRO63vsRs9/pZeU5i0dT2KlmfUQX52HqYxSl16Zs
mZPfymkunyvZb4OLbphBId0al9rkUAF6YCnpnvCOf7ZE/wPzT1ASQ1wp2qMWOzR+
f9qwbOjoMMTZn54RH2WWa0cfJnFL/XJQwVdV03WSlPQwscPsAP5CNBHcxFLY+UWr
CLUM2pHwFL4lAoIBAB7aKm8YBTtmLkI8hdMiyjSwt28zQoaOj3JRoUv2Ba98GzEJ
Y5mj4aC16y83LpY5wtmzquI+cC1Ch/FPurVekRSpr++DrijQ8DUaoLOXOl9LC1gU
H0It2XgHL/Nho1Pyl0ZIatTQa+m1L1cwBay1XUXMNLJXpJFLROGpqSrXyo06jfQm
Vm7lac42Cs2/vGitJtgcFlr56XqCmq4B5Iv0/2eB0tqwdLFBjawRFyUKDX8pFhGk
f8RQusimZhu54yge38yE2yMWGhDZhLwH3HG/yOb08bLKgRJFgNCEZ7O4k6XCM3hq
YDsZT0yBglk26Evr+lAcqdQxmGBJmf/gsfgPUg0CggEBAL7kfR113x9yUKgmdE/L
UcWmRDtMee1YKiOjf3MHm3o9Gj9a3kAYAJlldZ2vdcm/JKMPTGfo2DBy0ns/AjXf
wDQaMb9g9QzcgQKJJxobOIXJQeu/swvGW9n34N83OaN408nph+GfPinTnmoud7TF
maYkAUP2tHYtnlVR/dBuoHFifAekGnyCn+u6yKKeWE6OxrcYpmUXHvuL4nNMmUW8
nYMb9pRyKaXX4iwnfoO7CN+WgWj6kXXiUDDPp/MFXZDnvPNxcMmvJ/pU25EHSSgB
3S/PUj3h8lFSIc4tOBhPOIEpv5dl8zkG4Kxf2DMy1vigKO9/uGiQv3hoXlMB9T0T
0uUCggEBAM4vpNtuLYnFeqew5WW2vVJbrbnNAsKwWjQTvrKpD2UX+O1B/xf/4kAA
U0Ec/4d1JGIVdcBdF91PLW6blcpjDGQbOl9sAAT83HCGd7V7HJrTQzBEbgSQvEGo
DUL6HpkToexxZAMGU7gAvM8K4IuW23InwxmPpCPUnetgOVO5bwe/vGepg4OqcVgF
tTcOAuZs4RbCQY/yXmlKGhgRxIzq6OjdF1hBvSw/LHjXYqe+OxKJ5SEB5A7w3bYe
3Q+e6A1UIZK9t5TDEX5EtG9qIEQpoBUo4nYnF4nY1Ib++ux2Vp7tofBGOpbIXhZR
pGwRUuwWxj5bP9xxvBx/JDS1r4y8TrU=
-----END PRIVATE KEY-----
'''

PUBLIC_KEY = '''-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAzJD22nBYQ+yIwPE7wpGA
MSZFZHqvi3/Dll38kHckzGoCCNYm8grvIGPis+E+4noVOIPLM0x2HwdcCHgOA3Kz
9U+TJQk9UuJxaSkXTv3FV0VB6aOW8vYO3Iww/fqALvd6DhXOJacfQ+BDGjTUxGp6
RQntj29wJ1UuqZDBrVyZCZMTMaB913ZtJ9KNMNpst3ZT6X3cHinbXtk8wnSheVRX
lb7lBX7hK/6/L3VfY9eZW8wo366i5MYbn6Fv5onxR0sK7j+zBYsGxy2WqBwaQAB9
dSsjZ93NeNBnnKG8e8czYQGWNT0+9h57XdtzKP0rnzLbNJH9tGN9liLljtf0LdMF
XyzZWfesgd5Y9cuygmRUDH0CrzmKqRoqla37fOKzIWvsbKDPv7gdDrund5A6WY+k
7ahoSkjLMQ6uf+Qw3YOy5OlPS3RzPIuhY5Jrk4hAfUv1OKmBzKQiIeNBcAG+8A5B
SsKYaAhn+soqwERJtIDjILHUJGPWDo2gjlXt93SmUztviiS7wo0ikX9HLmuW0ZE8
i2xT9MmXiu98+Xbx69sa9d0APzoTpNw+XzpCPws5QhbqVbV5bnzoVv6aLEtJl7n6
4s9gKCLXTFiBBGl6Pu6FxaV3TmyfXw3x7MQ/FRrtNDigk+7HmdsROmMo9sMMKhko
TFw3SszldF9yeot97+WH+nkCAwEAAQ==
-----END PUBLIC KEY-----
'''
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'filehandling',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Add this at the top
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True
ROOT_URLCONF = 'oct14_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oct14_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Allow up to 5GB for file uploads
DATA_UPLOAD_MAX_MEMORY_SIZE = 5368709120  # 5 GB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 5368709120  # 5 GB in bytes

